### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [mizunotlt/transpose#1]
1. Вы не исправили вывод отсутствующих элементов.
1. Уберите [тут](https://github.com/mizunotlt/transpose/blob/master/src/transpose/transpose.java#L69) два лишних `toString()`.

**Comment by mizunotlt** [comment]
исправил

**Comment by maximpetrov** [comment]
1. Удалять все пробелы из конца строки не требуется, даже, пожалуй, неправильно, ведь они представляют отсутствующие в соответствующих строках элементы. Удалить нужно только последний лишний пробел, как Вы раньше и делали.
1. Под исправлением вывода отсутствующих элементов, я подразумевал, что при заданной ширине столбца, отсутствующие элементы должны быть строкой из пробелов соответствующей длины. Сейчас у Вас отсутствующие элементы всегда заменяются на пустую строку.
1. Тесты должны проверять работу во всех комбинациях параметров, а у Вас три раза проверяется одна и та же комбинация.

**Comment by mizunotlt** [comment]
исправил

**Comment by maximpetrov** [comment]
Тесты сейчас покрывают только 2 комбинации параметров из 4. Кроме того, в тестирование `cmdLine` неплохо бы включить проверку автоподстановки 10 для ширины, если она не задана при задании `cut` или `right`.

**Comment by mizunotlt** [comment]
сделал
